package:
  name: defuse
  version: '0.7.0'

source:
  git_url: https://dranew@bitbucket.org/dranew/defuse.git
  git_rev: v0.7.0

requirements:
  build:
    - perl
    - boost_source ==1.60.0

  run:
    - perl

about:
  home: http://bitbucket.org/dranew/defuse
  summary: 'Bioinformatics tool for gene fusion discovery using RNA-Seq data'

