package:
  name: defuse
  version: '0.8.2'

source:
  git_url: https://github.com/amcpherson/defuse.git
  git_rev: v0.8.2

requirements:
  build:
    - boost_source ==1.60.0

  run:
    - r
    - r-ada
    - blat
    - samtools
    - ucsc-fatotwobit
    - bowtie
    - gmap

about:
  home: https://github.com/amcpherson/defuse.git
  summary: 'Bioinformatics tool for gene fusion discovery using RNA-Seq data'

